### ISSUE TITLE
Create navigation

### ISSUE THREAD

**Issue by hannakozak** [chingu-voyages/v42-toucans-team-07#14]
**__Task Description__**
Add navigation to our app. Use figma design for ideas.

**__Technical Considerations__**
Make navigation responsive and stick yo the top of page

**__Additional Considerations__**
[https://www.figma.com/file/xXmQGWA75w69ub9AbTEW6e/Untitled?node-id=0%3A1](url)

**Comment by JatinKumar001** [comment]
Hey, can I start working on it.

**Comment by hannakozak** [comment]
You don't have to ask me. Choose whatever you want and create another
branch for your task. Can we use discord channel for communication?

**Comment by hannakozak** [comment]
Are you with our team?

**Comment by hannakozak** [comment]
Close because is done in different task
